from __future__ import annotations

import os

import invoke


_ALEMBIC_INI = "src/sentinel/data/migrations/alembic.ini"


@invoke.task
def run_migrations(ctx: invoke.Context) -> None:
    """
    Run all pending database migrations.
    """
    ctx.run(f"uv run alembic -c {_ALEMBIC_INI} upgrade head")


@invoke.task
def downgrade_migration(ctx: invoke.Context) -> None:
    """
    Undo the latest database migration.
    """
    ctx.run(f"uv run alembic -c {_ALEMBIC_INI} downgrade -1")


@invoke.task(help={"message": "Short description for the migration (e.g. 'add user table')"})
def build_migration(ctx: invoke.Context, message: str) -> None:
    """
    Create a new autogenerated database migration.
    """
    ctx.run(f"uv run alembic -c {_ALEMBIC_INI} revision --autogenerate -m '{message}'")


@invoke.task
def reset(ctx: invoke.Context) -> None:
    """
    Drop and recreate the local sentinel database, then run all migrations.
    """
    ctx.run("dropdb sentinel --if-exists")
    ctx.run("createdb sentinel")
    run_migrations(ctx)


@invoke.task
def check_missing_migrations(ctx: invoke.Context) -> None:
    """
    Verify no model changes are missing a migration (used in CI).
    """
    ctx.run("dropdb sentinel-migrations-tests --if-exists")
    ctx.run("createdb sentinel-migrations-tests")

    env = os.environ.copy()
    env["DATABASE_URL"] = "postgresql+asyncpg://postgres@localhost/sentinel-migrations-tests"

    ctx.run(f"uv run alembic -c {_ALEMBIC_INI} upgrade head", env=env)
    ctx.run(f"uv run alembic -c {_ALEMBIC_INI} check", env=env)
