apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: order-processor
  labels:
    app.kubernetes.io/name: order-processor
    app.kubernetes.io/instance: order-processor
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: order-processor
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: order-processor
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
      ports:
        - protocol: TCP
          port: 53
