apiVersion: v1
kind: Service
metadata:
  name: order-processor
  labels:
    app.kubernetes.io/name: order-processor
    app.kubernetes.io/instance: order-processor
    team: backend
spec:
  selector:
    app.kubernetes.io/name: order-processor
    app.kubernetes.io/instance: order-processor
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
